http:
  port: "8081"
sfdc:
  username: "***"
  password: "***"
  token: "***"
file:
  accountsDir:  "/MUFundamentals4.2_studentFiles_27jul2019/resources"
db:
  host: "mudb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"